
import { Activity, LevelId, ActivityType } from './types';

export const ACTIVITIES: Activity[] = [
  // EASY LEVEL: Select correct word
  {
    id: 'e1',
    levelId: LevelId.EASY,
    type: ActivityType.IMAGE_CHOICE,
    imageUrl: 'https://picsum.photos/seed/orange/400/400',
    instruction: 'Elige la palabra correcta que muestra la imagen.',
    correctAnswer: 'naranja',
    options: ['caranja', 'naranja'],
  },
  {
    id: 'e2',
    levelId: LevelId.EASY,
    type: ActivityType.IMAGE_CHOICE,
    imageUrl: 'https://picsum.photos/seed/elephant/400/400',
    instruction: 'Elige la palabra correcta que muestra la imagen.',
    correctAnswer: 'elefante',
    options: ['elefante', 'elefanve'],
  },
  {
    id: 'e3',
    levelId: LevelId.EASY,
    type: ActivityType.IMAGE_CHOICE,
    imageUrl: 'https://picsum.photos/seed/icecream/400/400',
    instruction: 'Elige la palabra correcta que muestra la imagen.',
    correctAnswer: 'helado',
    options: ['helado', 'hegalo'],
  },
  {
    id: 'e4',
    levelId: LevelId.EASY,
    type: ActivityType.IMAGE_CHOICE,
    imageUrl: 'https://picsum.photos/seed/scissors/400/400',
    instruction: 'Elige la palabra correcta que muestra la imagen.',
    correctAnswer: 'tijeras',
    options: ['tijeras', 'tiseras'],
  },
  {
    id: 'e5',
    levelId: LevelId.EASY,
    type: ActivityType.IMAGE_CHOICE,
    imageUrl: 'https://picsum.photos/seed/star/400/400',
    instruction: 'Elige la palabra correcta que muestra la imagen.',
    correctAnswer: 'estrella',
    options: ['estrella', 'esprella'],
  },
  {
    id: 'e6',
    levelId: LevelId.EASY,
    type: ActivityType.IMAGE_CHOICE,
    imageUrl: 'https://picsum.photos/seed/truck/400/400',
    instruction: 'Mira bien, ¿cuál de estas palabras describe el dibujo?',
    correctAnswer: 'camión',
    options: ['camión', 'tamón'],
  },
  {
    id: 'e7',
    levelId: LevelId.EASY,
    type: ActivityType.IMAGE_CHOICE,
    imageUrl: 'https://picsum.photos/seed/bird/400/400',
    instruction: '¡Qué lindo animal! ¿Cómo se llama?',
    correctAnswer: 'pájaro',
    options: ['fájaro', 'pájaro'],
  },
  {
    id: 'e8',
    levelId: LevelId.EASY,
    type: ActivityType.IMAGE_CHOICE,
    imageUrl: 'https://picsum.photos/seed/shoe/400/400',
    instruction: '¿Qué es lo que nos ponemos en los pies?',
    correctAnswer: 'zapato',
    options: ['zapato', 'sapato'],
  },
  {
    id: 'e9',
    levelId: LevelId.EASY,
    type: ActivityType.IMAGE_CHOICE,
    imageUrl: 'https://picsum.photos/seed/butterfly/400/400',
    instruction: 'Tiene alas de muchos colores, elige su nombre.',
    correctAnswer: 'mariposa',
    options: ['maliposa', 'mariposa'],
  },
  {
    id: 'e10',
    levelId: LevelId.EASY,
    type: ActivityType.IMAGE_CHOICE,
    imageUrl: 'https://picsum.photos/seed/ball/400/400',
    instruction: 'Sirve para jugar al fútbol, ¿qué es?',
    correctAnswer: 'pelota',
    options: ['pelota', 'belota'],
  },

  // MEDIUM LEVEL: Repeat word
  {
    id: 'm1',
    levelId: LevelId.MEDIUM,
    type: ActivityType.REPEAT_WORD,
    imageUrl: 'https://picsum.photos/seed/apple/400/400',
    instruction: 'Mira la imagen y repite conmigo la siguiente palabra: manzana.',
    correctAnswer: 'manzana',
    word: 'manzana',
  },
  {
    id: 'm2',
    levelId: LevelId.MEDIUM,
    type: ActivityType.REPEAT_WORD,
    imageUrl: 'https://picsum.photos/seed/banana/400/400',
    instruction: 'Mira la imagen y repite conmigo la siguiente palabra: plátano.',
    correctAnswer: 'plátano',
    word: 'plátano',
  },
  {
    id: 'm3',
    levelId: LevelId.MEDIUM,
    type: ActivityType.REPEAT_WORD,
    imageUrl: 'https://picsum.photos/seed/car/400/400',
    instruction: 'Mira la imagen y repite conmigo la siguiente palabra: coche.',
    correctAnswer: 'coche',
    word: 'coche',
  },
  {
    id: 'm4',
    levelId: LevelId.MEDIUM,
    type: ActivityType.REPEAT_WORD,
    imageUrl: 'https://picsum.photos/seed/dog/400/400',
    instruction: 'Mira la imagen y repite conmigo la siguiente palabra: perro.',
    correctAnswer: 'perro',
    word: 'perro',
  },
  {
    id: 'm5',
    levelId: LevelId.MEDIUM,
    type: ActivityType.REPEAT_WORD,
    imageUrl: 'https://picsum.photos/seed/cat/400/400',
    instruction: 'Mira la imagen y repite conmigo la siguiente palabra: gato.',
    correctAnswer: 'gato',
    word: 'gato',
  },
  {
    id: 'm6',
    levelId: LevelId.MEDIUM,
    type: ActivityType.REPEAT_WORD,
    imageUrl: 'https://picsum.photos/seed/bicycle/400/400',
    instruction: '¡Vamos a pedalear! Di con calma: Bi-ci-cle-ta.',
    correctAnswer: 'bicicleta',
    word: 'bicicleta',
  },
  {
    id: 'm7',
    levelId: LevelId.MEDIUM,
    type: ActivityType.REPEAT_WORD,
    imageUrl: 'https://picsum.photos/seed/dinosaur/400/400',
    instruction: 'Un animal muy grande del pasado. Repite: Di-no-sau-rio.',
    correctAnswer: 'dinosaurio',
    word: 'dinosaurio',
  },
  {
    id: 'm8',
    levelId: LevelId.MEDIUM,
    type: ActivityType.REPEAT_WORD,
    imageUrl: 'https://picsum.photos/seed/computer/400/400',
    instruction: 'Sirve para estudiar y jugar. Di conmigo: Com-pu-ta-do-ra.',
    correctAnswer: 'computadora',
    word: 'computadora',
  },

  // HARD LEVEL: Complete word
  {
    id: 'h1',
    levelId: LevelId.HARD,
    type: ActivityType.BUILD_WORD,
    imageUrl: 'https://picsum.photos/seed/cat_small/400/400',
    instruction: 'Completa la palabra que muestra la imagen.',
    correctAnswer: 'gato',
    fullWord: 'gato',
    missingLetters: ['a'],
    options: ['a', 'e', 'i', 'o'],
  },
  {
    id: 'h2',
    levelId: LevelId.HARD,
    type: ActivityType.BUILD_WORD,
    imageUrl: 'https://picsum.photos/seed/dog_small/400/400',
    instruction: 'Completa la palabra que muestra la imagen.',
    correctAnswer: 'perro',
    fullWord: 'perro',
    missingLetters: ['r'],
    options: ['r', 'l', 'm'],
  },
  {
    id: 'h3',
    levelId: LevelId.HARD,
    type: ActivityType.BUILD_WORD,
    imageUrl: 'https://picsum.photos/seed/house/400/400',
    instruction: 'Completa la palabra que muestra la imagen.',
    correctAnswer: 'casa',
    fullWord: 'casa',
    missingLetters: ['s'],
    options: ['s', 'm', 'l'],
  },
  {
    id: 'h4',
    levelId: LevelId.HARD,
    type: ActivityType.BUILD_WORD,
    imageUrl: 'https://picsum.photos/seed/sun/400/400',
    instruction: 'Completa la palabra que muestra la imagen.',
    correctAnswer: 'sol',
    fullWord: 'sol',
    missingLetters: ['o'],
    options: ['a', 'e', 'o'],
  },
  {
    id: 'h5',
    levelId: LevelId.HARD,
    type: ActivityType.BUILD_WORD,
    imageUrl: 'https://picsum.photos/seed/moon/400/400',
    instruction: 'Completa la palabra que muestra la imagen.',
    correctAnswer: 'luna',
    fullWord: 'luna',
    missingLetters: ['u'],
    options: ['u', 'i', 'a'],
  },
  {
    id: 'h6',
    levelId: LevelId.HARD,
    type: ActivityType.BUILD_WORD,
    imageUrl: 'https://picsum.photos/seed/umbrella/400/400',
    instruction: 'Nos protege de la lluvia. Completa la letra que falta.',
    correctAnswer: 'paraguas',
    fullWord: 'paraguas',
    missingLetters: ['g'],
    options: ['g', 'j', 'b'],
  },
  {
    id: 'h7',
    levelId: LevelId.HARD,
    type: ActivityType.BUILD_WORD,
    imageUrl: 'https://picsum.photos/seed/phone/400/400',
    instruction: 'Sirve para llamar a mamá o papá. ¿Qué letra falta?',
    correctAnswer: 'teléfono',
    fullWord: 'teléfono',
    missingLetters: ['f'],
    options: ['f', 'p', 't'],
  },
];
